name: Hello, World!
on:
  push:
    paths:
      - '**.php'

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    if: contains(github.ref, 'master')
    steps:
      - run: echo "Hello, World!"
